resources:
  - name: src
    type: GitRepo
    configuration:
      gitProvider: ranjithr_github
      path: ranjithrs/basic-node

pipelines:
  - name: ranjithr_pipeline
    steps:
      - name: build
        type: Bash
        configuration:
          nodePool: ranjithr_pool
          runtime:
            type: image
            image:
             custom:
               name: drydock/u16nodall
               tag: v7.2.4
          inputResources:
            - name: src
        execution:
          onExecute:
            - env | sort
            - cd $res_src_resourcePath
            - shippable_retry npm install
            - mkdir -p shippable/testresults && mkdir -p shippable/codecoverage
            - $res_src_resourcePath/node_modules/.bin/mocha --recursive "tests/**/*.spec.js" -R mocha-junit-reporter --reporter-options mochaFile=shippable/testresults/testresults.xml
            - $res_src_resourcePath/node_modules/.bin/istanbul --include-all-sources cover -root "routes" node_modules/mocha/bin/_mocha -- -R spec-xunit-file --recursive "tests/**/*.spec.js"
            - $res_src_resourcePath/node_modules/.bin/istanbul report cobertura --dir shippable/codecoverage
            - save_tests $res_src_resourcePath/shippable/testresults/testresults.xml
      - name: unit_test
        type: Bash
        configuration:
          nodePool: ranjithr_pool        
          inputSteps:
            - name: build
        execution:
          onExecute:
            - echo "Unit Test completed"
      - name: xray_scan
        type: Bash
        configuration:
          nodePool: ranjithr_pool        
          inputSteps:
            - name: build
        execution:
          onExecute:
            - echo "Xray scan completed"
      - name: publish_artifacts
        type: Bash
        configuration:
          nodePool: ranjithr_pool        
          inputSteps:
            - name: unit_test
            - name: xray_scan
        execution:
          onExecute:
            - echo "Publish to RT completed"
