resources:
  - name: src
    type: gitRepo
    repoPath: ranjithrs/basic-node
    configuration:
      integrationName: ranjithr_github
    version:
      sha: master

pipelines:
  - name: ranjithr_pipeline
    steps:
      - name: build
        type: bash
        configuration:
          nodePool: ranjithr_pool
        setup:   
          runtime:
            type: image
            image:
             custom:
               name: drydock/u16nodall
               tag: v7.2.4
        triggeredBy:
          resources:
            - src
        execution:
          onExecute:
            - env
            - cd $res_src_resourcePath
            - shippable_retry npm install
            - sleep 10
            - mkdir -p shippable/testresults && mkdir -p shippable/codecoverage
            - $res_src_resourcePath/node_modules/.bin/mocha --recursive "tests/**/*.spec.js" -R mocha-junit-reporter --reporter-options mochaFile=shippable/testresults/testresults.xml
            - $res_src_resourcePath/node_modules/.bin/istanbul --include-all-sources cover -root "routes" node_modules/mocha/bin/_mocha -- -R spec-xunit-file --recursive "tests/**/*.spec.js"
            - $res_src_resourcePath/node_modules/.bin/istanbul report cobertura --dir shippable/codecoverage
            - save_tests $res_src_resourcePath/shippable/testresults/testresults.xml
      - name: unit_test
        type: bash
        configuration:
          nodePool: ranjithr_pool        
        setup:   
          runtime:
            type: image
            image:
             custom:
               name: drydock/u16nodall
               tag: v7.2.4
        triggeredBy:
          steps:
            - build
        execution:
          onExecute:
            - echo "Unit Test completed"
      - name: xray_scan
        type: bash
        configuration:
          nodePool: ranjithr_pool        
        setup:   
          runtime:
            type: image
            image:
             custom:
               name: drydock/u16nodall
               tag: v7.2.4
        triggeredBy:
          steps:
            - build
        execution:
          onExecute:
            - echo "Xray scan completed"
      - name: publish_artifacts
        type: bash
        configuration:
          nodePool: ranjithr_pool        
        setup:   
          runtime:
            type: image
            image:
             custom:
               name: drydock/u16nodall
               tag: v7.2.4
        triggeredBy:
          steps:
            - unit_test
            - xray_scan
        execution:
          onExecute:
            - echo "Publish to RT completed"
