resources:
  - name: src
    type: gitRepo
    repoPath: ranjithrs/basic-node
    configuration:
      integrationName: ranjithr_github
    initialVersion:
      sha: master

pipelines:
  - name: ranjithr_pipeline
    steps:
      - name: build
        type: bash
        setup:
          runtime:
            type: image
            image:
             auto:
               language: nodejs
        triggeredBy:
          resources:
            - src
        execution:
          onExecute:
            - shippable_retry npm install
            - mkdir -p $TEST_RESULTS_DIR && mkdir -p $CODE_COVERAGE_DIR
            - pushd $TESTS_LOC_DIR
            - $MOD_LOC/mocha --recursive "$TESTS_LOC_DIR/**/*.spec.js" -R mocha-junit-reporter --reporter-options mochaFile=$TEST_RESULTS_DIR/testresults.xml
            - $MOD_LOC/istanbul --include-all-sources cover -root "$SHIPPABLE_REPO_DIR/routes" $SHIPPABLE_REPO_DIR/node_modules/mocha/bin/_mocha -- -R spec-xunit-file --recursive "$TESTS_LOC_DIR/**/*.spec.js"
            - $MOD_LOC/istanbul report cobertura --dir $CODE_COVERAGE_DIR
            - popd
 
