resources:
  - name: src
    type: gitRepo
    repoPath: ranjithrs/basic-node
    configuration:
      integrationName: ranjithr_github
    initialVersion:
      sha: master

pipelines:
  - name: ranjithr_pipeline
    steps:
      - name: build
        type: bash
        setup:   
          runtime:
            type: image
            image:
             custom:
               name: drydock/u16nodall
               tag: v7.2.4
        triggeredBy:
          resources:
            - src
        execution:
          onExecute:
            - cd $res_src_resourcePath
            - shippable_retry npm install
            - mkdir -p shippable/testresults && mkdir -p shippable/codecoverage
            - pushd tests
            - node_modules/.bin/mocha --recursive "tests/**/*.spec.js" -R mocha-junit-reporter --reporter-options mochaFile=shippable/testresults/testresults.xml
            - node_modules/.bin/istanbul --include-all-sources cover -root "routes" node_modules/mocha/bin/_mocha -- -R spec-xunit-file --recursive "tests/**/*.spec.js"
            - node_modules/.bin/istanbul report cobertura --dir shippable/codecoverage
            - popd
 
